chore: fix build issue with various versions of cssparser dep
Updating oxvg_* crates 0.0.5 -> 0.0.7 gave this

error: failed to select a version for `lightningcss`.
    ... required by package `oxvg_collections v0.0.5`
    ... which satisfies dependency `oxvg_collections = ">=0.0"` (locked to 0.0.5) of package `oxvg_ast v0.0.7`
    ... which satisfies dependency `oxvg_ast = "^0.0.7"` of package `dme-core v0.1.0 (/home/sam/code/dme/app/core)`
    ... which satisfies path dependency `dme-core` (locked to 0.1.0) of package `delibay v0.0.2 (/home/sam/code/delibay/desktop)`
versions that meet the requirements `^1.0.0-alpha.63` (locked to 1.0.0-alpha.65) are: 1.0.0-alpha.65

all possible versions conflict with previously selected packages

  previously selected package `lightningcss v1.0.0-alpha.72`
    ... which satisfies dependency `lightningcss = "^1.0.0-alpha.72"` of package `oxvg_ast v0.0.7`
    ... which satisfies dependency `oxvg_ast = "^0.0.7"` of package `dme-core v0.1.0 (/home/sam/code/dme/app/core)`
    ... which satisfies path dependency `dme-core` (locked to 0.1.0) of package `delibay v0.0.2 (/home/sam/code/delibay/desktop)`

This was fixed with

cargo update -p oxvg_ast
cargo update -p oxvg_optimiser